import type { Metadata } from "next";
import Link from "next/link";
import { Shell } from "@/components/site/Shell";
import { Page } from "@/components/site/Page";
import { FadeIn } from "@/components/animations/FadeIn";
import { ScaleIn } from "@/components/animations/ScaleIn";
import { PDFButton } from "@/components/site/research/PDFButton";

export const metadata: Metadata = {
  title: "FLT3-AML Research Program | Aternox",
  description:
    "DGS produced a complete preclinical research architecture for FLT3-mutated AML — 58 documents, one run. View the program scope and request access.",
};

const programNodes = [
  {
    id: "N1",
    title: "Target Engagement Contracts",
    body: "Evidence protocols establishing the criteria for confirmed FLT3 binding and target engagement.",
  },
  {
    id: "N2",
    title: "Selectivity Separation",
    body: "Plans to distinguish on-target FLT3 effects from off-target and non-specific cytotoxicity.",
  },
  {
    id: "N3",
    title: "Off-Target Screening",
    body: "Counter-screen architecture to identify and eliminate compounds with off-target activity.",
  },
  {
    id: "N4",
    title: "Resistance Mechanisms",
    body: "Failure playbooks for six known FLT3 resistance mechanisms including TKD mutations and pathway bypass.",
  },
  {
    id: "N5",
    title: "Safety Risk Discovery",
    body: "Preclinical safety assessment architecture covering hepatotoxicity, cardiotoxicity, and genotoxicity risk.",
  },
  {
    id: "N6",
    title: "Stage 0–4 Development Plan",
    body: "Master development plan from target hypothesis through IND-enabling studies. Full stage gate logic included.",
  },
  {
    id: "N7",
    title: "Agent Class Specification",
    body: "Structural and mechanistic criteria for the class of FLT3 inhibitor this program targets.",
  },
  {
    id: "N8",
    title: "Translational Feasibility",
    body: "Assessment of the path from preclinical architecture to clinical hypothesis. No clinical claims made.",
  },
  {
    id: "N9",
    title: "Confounder Blocking",
    body: "Pre-specified confounder identification and blocking protocols across all major experiment types.",
  },
  {
    id: "N10",
    title: "Falsification Matrix",
    body: "Six pre-specified failure modes with deterministic routing — what happens if each one triggers.",
  },
  {
    id: "N11",
    title: "Gate 0 Reality Check",
    body: "Independent stress-test of the entire program architecture before Stage 0 execution begins.",
  },
];

const keyDocuments = [
  {
    id: "ENG-001",
    title: "Target Engagement Evidence Contract",
    body: "Defines the exact evidentiary standard for confirmed FLT3 target engagement. Pre-specified before any assay is run.",
  },
  {
    id: "SEL-001",
    title: "Selectivity and Non-Specific Kill Separation",
    body: "The protocol for isolating genuine FLT3 selectivity from non-specific cytotoxic effects.",
  },
  {
    id: "OFF-001",
    title: "Off-Target Counter-Screen Plan",
    body: "Full counter-screen architecture. Identifies which off-target assays run, at what thresholds, and what the failure criteria are.",
  },
  {
    id: "SAFE-001",
    title: "Preclinical Safety Risk Discovery Plan",
    body: "Risk-first safety architecture. Identifies the three highest-probability safety failure modes and builds testing around them.",
  },
  {
    id: "DEV-001",
    title: "Stage 0–4 Development Master Plan",
    body: "The complete program roadmap from target hypothesis to IND-enabling studies. Every stage gate is pre-specified.",
  },
];

export default function ResearchPage() {
  return (
    <Shell>
      <Page
        eyebrow="PROOF OF CONCEPT"
        title="FLT3-Mutated AML — Preclinical Research Architecture"
        subtitle="A complete deterministic preclinical research program generated by DGS. 58 structured documents across 11 program nodes."
      >
        {/* DISCLAIMER BOX */}
        <FadeIn>
          <div className="rounded-2xl border-2 border-white/20 bg-white/[0.04] p-6 mb-12">
            <div className="font-mono text-[10px] font-semibold uppercase tracking-widest text-white/50 mb-2">Research Scope — Disclaimer</div>
            <p className="text-sm leading-relaxed text-white/70">
              This program is a preclinical hypothesis and experiment architecture only. No laboratory data exists. No molecule has been synthesized. No clinical efficacy is claimed. This is not medical advice. Independent scientific validation is required before any conclusions are drawn.
            </p>
          </div>
        </FadeIn>

        {/* PROGRAM NODES */}
        <FadeIn delay={0.1}>
          <div className="mb-12">
            <div className="text-xs font-mono font-semibold uppercase tracking-wider text-muted mb-6">Program Nodes</div>
            <div className="grid gap-4 md:grid-cols-2">
              {programNodes.map((node, i) => (
                <ScaleIn key={node.id} delay={0.05 * i} className="rounded-2xl border border-border/70 bg-surface/50 p-6 glow">
                  <div className="font-mono text-[10px] font-semibold tracking-widest text-brand-2 uppercase">{node.id} — {node.title}</div>
                  <div className="mt-2 text-sm leading-relaxed text-muted">{node.body}</div>
                </ScaleIn>
              ))}
            </div>
          </div>
        </FadeIn>

        {/* KEY DOCUMENTS */}
        <FadeIn delay={0.3}>
          <div className="mb-12">
            <div className="text-xs font-mono font-semibold uppercase tracking-wider text-muted mb-6">Key Documents</div>
            <div className="space-y-3">
              {keyDocuments.map((doc, i) => (
                <ScaleIn key={doc.id} delay={0.07 * i} className="rounded-2xl border border-border/70 bg-surface/50 p-6 glow">
                  <div className="font-mono text-[10px] font-semibold tracking-widest text-brand-2 uppercase">{doc.id}: {doc.title}</div>
                  <div className="mt-2 text-sm leading-relaxed text-muted">{doc.body}</div>
                </ScaleIn>
              ))}
            </div>
          </div>
        </FadeIn>

        {/* ACCESS TIERS */}
        <FadeIn delay={0.5}>
          <div>
            <div className="text-xs font-mono font-semibold uppercase tracking-wider text-muted mb-6">Access Tiers</div>
            <div className="grid gap-5 md:grid-cols-3">
              <ScaleIn delay={0.1} className="rounded-3xl border border-border/70 bg-surface/50 p-8 transition-all duration-500 hover:scale-105 hover:border-brand-2/50 hover:bg-surface/70 glow">
                <div className="font-mono text-[10px] font-semibold uppercase tracking-wider text-muted">PUBLIC</div>
                <div className="mt-3 font-sans text-lg font-semibold tracking-[-0.04em]">One-page program summary</div>
                <p className="mt-4 text-sm text-muted">Available now. No NDA required. A single-page overview of the program scope, key documents, and stage architecture.</p>
                <div className="mt-6">
                  <PDFButton />
                </div>
              </ScaleIn>

              <ScaleIn delay={0.2} className="rounded-3xl border border-border/70 bg-surface/50 p-8 transition-all duration-500 hover:scale-105 hover:border-brand-2/50 hover:bg-surface/70 glow">
                <div className="font-mono text-[10px] font-semibold uppercase tracking-wider text-muted">NDA REQUIRED</div>
                <div className="mt-3 font-sans text-lg font-semibold tracking-[-0.04em]">Full program package — all 58 documents</div>
                <p className="mt-4 text-sm text-muted">Available to credentialed researchers and institutional partners. Requires a signed NDA. Submit a request and NDA documentation will follow within 48 hours.</p>
                <div className="mt-6">
                  <Link href="/contact" className="btn-secondary inline-flex h-12 items-center justify-center rounded-full px-5 text-sm font-semibold transition-all hover:scale-105">
                    Request access
                  </Link>
                </div>
              </ScaleIn>

              <ScaleIn delay={0.3} className="rounded-3xl border border-border/70 bg-surface/50 p-8 transition-all duration-500 hover:scale-105 hover:border-brand-2/50 hover:bg-surface/70 glow">
                <div className="font-mono text-[10px] font-semibold uppercase tracking-wider text-muted">LAB PARTNERSHIP</div>
                <div className="mt-3 font-sans text-lg font-semibold tracking-[-0.04em]">Stage 0 execution collaboration</div>
                <p className="mt-4 text-sm text-muted">For research groups who want to run the Stage 0–2 experiments against this architecture. Get in touch to discuss scope and feasibility.</p>
                <div className="mt-6">
                  <Link href="/contact" className="btn-secondary inline-flex h-12 items-center justify-center rounded-full px-5 text-sm font-semibold transition-all hover:scale-105">
                    Get in touch
                  </Link>
                </div>
              </ScaleIn>
            </div>
          </div>
        </FadeIn>

        {/* REPEAT DISCLAIMER at bottom */}
        <FadeIn delay={0.7}>
          <div className="mt-12 rounded-2xl border border-white/10 bg-white/[0.02] p-5">
            <p className="text-[11px] leading-relaxed text-white/30">
              Preclinical research architecture only. No laboratory data exists. No molecule has been synthesized. No clinical efficacy is claimed. This is not medical advice. Independent scientific validation is required before any conclusions are drawn.
            </p>
          </div>
        </FadeIn>
      </Page>
    </Shell>
  );
}
